import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import NextThemeProvider from '@/components/providers/theme-provider';
import { Toaster } from 'sonner';
import Header from '@/components/headers';
import Footer from '@/components/footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true} className="scroll-smooth">
            <body
                className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
            >
                <NextThemeProvider>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                    <Toaster />
                </NextThemeProvider>
            </body>
        </html>
    );
}
